services:
  evernote-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3443:3443"
    environment:
      - NODE_ENV=production
      - EVERNOTE_CONSUMER_KEY=${EVERNOTE_CONSUMER_KEY}
      - EVERNOTE_CONSUMER_SECRET=${EVERNOTE_CONSUMER_SECRET}
      - DEV_MODE=${DEV_MODE:-false}
      # OAuth tokens for persistent authentication
      - EVERNOTE_ACCESS_TOKEN=${EVERNOTE_ACCESS_TOKEN:-}
      - EVERNOTE_TOKEN_SECRET=${EVERNOTE_TOKEN_SECRET:-}
      - EVERNOTE_EDAM_SHARD=${EVERNOTE_EDAM_SHARD:-}
      - EVERNOTE_EDAM_USER_ID=${EVERNOTE_EDAM_USER_ID:-}
      - EVERNOTE_EDAM_EXPIRES=${EVERNOTE_EDAM_EXPIRES:-}
      - EVERNOTE_EDAM_NOTE_STORE_URL=${EVERNOTE_EDAM_NOTE_STORE_URL:-}
      - EVERNOTE_EDAM_WEB_API_URL_PREFIX=${EVERNOTE_EDAM_WEB_API_URL_PREFIX:-}
    healthcheck:
      test: ["CMD", "test", "-f", "/proc/1/stat"]
      interval: 45s
      timeout: 15s
      retries: 5
      start_period: 60s
